[WIP] Starting to add helpers
TryGhost/docs-old pull request #51
Opened 2018-12-04 18:03 UTC by ErisDS

only works when using `yarn link` 🤔

2018-12-06 21:05 UTC, ErisDS commented
@AileenCGN I've updated this PR 

@JohnONolan I don't think having generic react components is gonna work without quite a bit more playing (see PR desc). I think I will focus on having a more thorough suite of tools in @tryghost/helpers, and we can think about use cases for either @tryghost/helpers-react or @tryghost/helpers-gatsby when we get a bit further down the road.

2018-12-12 12:00 UTC, aileen requested changes
`separator` and `visibility` don't work as expected. See detailed comments

2018-12-12 12:00 UTC, aileen commented on src/components/common/Tags.js
> +*   - visibility [optional, default "all", the pattern used to control the if internal tags should be included]
@ErisDS I added the visibility attribute, but it doesn't work as expected for me. I tried
- `public` → renders nothing
- `all` → renders everything
- `internal` → renders nothing

2018-12-12 12:00 UTC, aileen commented on src/components/common/Tags.js
> +            <span className={props.separatorClasses}>{props.separator}</span>
There are two problems here:
1. When I want **no** separator, I'll pass `separator=""`, which will then still add the default `", "` separator [here](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/helpers/tags.js#L12):
![image](https://user-images.githubusercontent.com/8037602/49868156-76210580-fe04-11e8-9c54-6f2a17db4e30.png)

2. Adding a separator (even if it's a `" "` to workaround problem no. 1), but having more than one tag will cause a problem with the required `key` attributes for React children:

![image](https://user-images.githubusercontent.com/8037602/49868124-630e3580-fe04-11e8-8057-f3c1c1d50eda.png)

This is fine for `prefix` and `suffix` as these get only appended once.

2018-12-12 12:00 UTC, aileen commented on src/components/common/Tags.js
> +        let tagLink = props.permalink
We're getting linting errors here:

```
/Users/aileen/code/docs/src/components/common/Tags.js
  49:29  error  'permalink' is missing in props validation    react/prop-types
  52:22  error  'autolink' is missing in props validation     react/prop-types
  53:36  error  'classes' is missing in props validation      react/prop-types
  54:53  error  'linkClasses' is missing in props validation  react/prop-types
```

2018-12-12 12:01 UTC, AileenCGN commented on src/components/tutorials/TutorialCard.js
> +                    <Tags
This should result in the exact same output as before, but doesn't atm. Problems are the `visibility` attribute and the `separator` as mentioned above.

2018-12-12 15:40 UTC, ErisDS commented on src/components/common/Tags.js
> +        let tagLink = props.permalink
I have no idea why because they aren't missing?

2018-12-12 15:44 UTC, AileenCGN commented on src/components/common/Tags.js
> +        let tagLink = props.permalink
I _think_ it's because it's a separate fn maybe?

2019-01-04 06:58 UTC, rishabhgrg commented on src/components/common/Tags.js
> +            <span className={props.separatorClasses}>{props.separator}</span>
Separator issue was fixed in helper in https://github.com/TryGhost/Ghost-SDK/pull/30

2019-01-04 07:00 UTC, rishabhgrg commented on src/components/common/Tags.js
> +*   - visibility [optional, default "all", the pattern used to control the if internal tags should be included]
visibility attribute works now after fixes to visibility helpers in SDK now

2019-01-16 07:23 UTC, aileen approved these changes

2019-01-16 07:28 UTC, merged